spring:
    mvc:
        view:
            prefix: /WEB-INF/pages/
            suffix: .jsp

    datasource:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
        driver-class-name: org.h2.Driver
        data-username: sa
        data-password:
        platform: h2

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create-drop